// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dds_AIWebRTC.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "dds_AIWebRTC.h"

#include <ucdr/microcdr.h>
#include <string.h>



bool AIWebRTCEvent_serialize_topic(ucdrBuffer* writer, const AIWebRTCEvent* topic)
{
    bool success = true;

        success &= TimeStamp_serialize_topic(writer, &topic->stamp);
        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->event);

    return success && !writer->error;
}

bool AIWebRTCEvent_deserialize_topic(ucdrBuffer* reader, AIWebRTCEvent* topic)
{
    bool success = true;

        success &= TimeStamp_deserialize_topic(reader, &topic->stamp);
        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->event);

    return success && !reader->error;
}

uint32_t AIWebRTCEvent_size_of_topic(const AIWebRTCEvent* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += TimeStamp_size_of_topic(&topic->stamp, size);
        size += ucdr_alignment(size, 4) + 4;

    return size - previousSize;
}

bool AIWebRTCRequest_serialize_topic(ucdrBuffer* writer, const AIWebRTCRequest* topic)
{
    bool success = true;

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->command);

        for(size_t i = 0; i < sizeof(topic->destination) / 255; ++i)
        {
            success &= ucdr_serialize_string(writer, topic->destination[i]);
        }
        success &= ucdr_serialize_uint16_t(writer, topic->timeout_sec);

    return success && !writer->error;
}

bool AIWebRTCRequest_deserialize_topic(ucdrBuffer* reader, AIWebRTCRequest* topic)
{
    bool success = true;

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->command);

        for(size_t i = 0; i < sizeof(topic->destination) / 255; ++i)
        {
            success &= ucdr_deserialize_string(reader, topic->destination[i], 255);
        }
        success &= ucdr_deserialize_uint16_t(reader, &topic->timeout_sec);

    return success && !reader->error;
}

uint32_t AIWebRTCRequest_size_of_topic(const AIWebRTCRequest* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

        for(size_t i = 0; i < sizeof(topic->destination) / 255; ++i)
        {
            size += ucdr_alignment(size, 4) + 4 + (uint32_t)strlen(topic->destination[i]) + 1;
        }
        size += ucdr_alignment(size, 2) + 2;

    return size - previousSize;
}

bool AIWebRTCResponse_serialize_topic(ucdrBuffer* writer, const AIWebRTCResponse* topic)
{
    bool success = true;

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->command);

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->code);

        for(size_t i = 0; i < sizeof(topic->destination) / 255; ++i)
        {
            success &= ucdr_serialize_string(writer, topic->destination[i]);
        }
        success &= ucdr_serialize_uint16_t(writer, topic->timeout_sec);

    return success && !writer->error;
}

bool AIWebRTCResponse_deserialize_topic(ucdrBuffer* reader, AIWebRTCResponse* topic)
{
    bool success = true;

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->command);

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->code);

        for(size_t i = 0; i < sizeof(topic->destination) / 255; ++i)
        {
            success &= ucdr_deserialize_string(reader, topic->destination[i], 255);
        }
        success &= ucdr_deserialize_uint16_t(reader, &topic->timeout_sec);

    return success && !reader->error;
}

uint32_t AIWebRTCResponse_size_of_topic(const AIWebRTCResponse* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

        size += ucdr_alignment(size, 4) + 4;

        for(size_t i = 0; i < sizeof(topic->destination) / 255; ++i)
        {
            size += ucdr_alignment(size, 4) + 4 + (uint32_t)strlen(topic->destination[i]) + 1;
        }
        size += ucdr_alignment(size, 2) + 2;

    return size - previousSize;
}
