// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dds_Log.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "dds_Log.h"

#include <ucdr/microcdr.h>
#include <string.h>


bool Log_serialize_topic(ucdrBuffer* writer, const Log* topic)
{
    bool success = true;

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->level);

        success &= TimeStamp_serialize_topic(writer, &topic->stamp);
        success &= ucdr_serialize_string(writer, topic->topic);

        success &= ucdr_serialize_string(writer, topic->value);

    return success && !writer->error;
}

bool Log_deserialize_topic(ucdrBuffer* reader, Log* topic)
{
    bool success = true;

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->level);

        success &= TimeStamp_deserialize_topic(reader, &topic->stamp);
        success &= ucdr_deserialize_string(reader, topic->topic, 255);

        success &= ucdr_deserialize_string(reader, topic->value, 255);

    return success && !reader->error;
}

uint32_t Log_size_of_topic(const Log* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

        size += TimeStamp_size_of_topic(&topic->stamp, size);
        size += ucdr_alignment(size, 4) + 4 + (uint32_t)strlen(topic->topic) + 1;

        size += ucdr_alignment(size, 4) + 4 + (uint32_t)strlen(topic->value) + 1;

    return size - previousSize;
}
