// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dds_Sensor.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "dds_Sensor.h"

#include <ucdr/microcdr.h>
#include <string.h>



bool SensorEvent_serialize_topic(ucdrBuffer* writer, const SensorEvent* topic)
{
    bool success = true;

        success &= TimeStamp_serialize_topic(writer, &topic->stamp);
        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->type);

        success &= ucdr_serialize_uint16_t(writer, topic->timeout_sec);

    return success && !writer->error;
}

bool SensorEvent_deserialize_topic(ucdrBuffer* reader, SensorEvent* topic)
{
    bool success = true;

        success &= TimeStamp_deserialize_topic(reader, &topic->stamp);
        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->type);

        success &= ucdr_deserialize_uint16_t(reader, &topic->timeout_sec);

    return success && !reader->error;
}

uint32_t SensorEvent_size_of_topic(const SensorEvent* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += TimeStamp_size_of_topic(&topic->stamp, size);
        size += ucdr_alignment(size, 4) + 4;

        size += ucdr_alignment(size, 2) + 2;

    return size - previousSize;
}

bool SensorRequest_serialize_topic(ucdrBuffer* writer, const SensorRequest* topic)
{
    bool success = true;

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->command);

    return success && !writer->error;
}

bool SensorRequest_deserialize_topic(ucdrBuffer* reader, SensorRequest* topic)
{
    bool success = true;

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->command);

    return success && !reader->error;
}

uint32_t SensorRequest_size_of_topic(const SensorRequest* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

    return size - previousSize;
}

bool SensorResponse_serialize_topic(ucdrBuffer* writer, const SensorResponse* topic)
{
    bool success = true;

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->command);

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->code);

    return success && !writer->error;
}

bool SensorResponse_deserialize_topic(ucdrBuffer* reader, SensorResponse* topic)
{
    bool success = true;

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->command);

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->code);

    return success && !reader->error;
}

uint32_t SensorResponse_size_of_topic(const SensorResponse* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

        size += ucdr_alignment(size, 4) + 4;

    return size - previousSize;
}
