// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dds_QR.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "dds_QR.h"

#include <ucdr/microcdr.h>
#include <string.h>



bool QRReadEvent_serialize_topic(ucdrBuffer* writer, const QRReadEvent* topic)
{
    bool success = true;

        success &= TimeStamp_serialize_topic(writer, &topic->stamp);
        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->event);

        for(size_t i = 0; i < sizeof(topic->read_string) / 255; ++i)
        {
            success &= ucdr_serialize_string(writer, topic->read_string[i]);
        }
    return success && !writer->error;
}

bool QRReadEvent_deserialize_topic(ucdrBuffer* reader, QRReadEvent* topic)
{
    bool success = true;

        success &= TimeStamp_deserialize_topic(reader, &topic->stamp);
        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->event);

        for(size_t i = 0; i < sizeof(topic->read_string) / 255; ++i)
        {
            success &= ucdr_deserialize_string(reader, topic->read_string[i], 255);
        }
    return success && !reader->error;
}

uint32_t QRReadEvent_size_of_topic(const QRReadEvent* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += TimeStamp_size_of_topic(&topic->stamp, size);
        size += ucdr_alignment(size, 4) + 4;

        for(size_t i = 0; i < sizeof(topic->read_string) / 255; ++i)
        {
            size += ucdr_alignment(size, 4) + 4 + (uint32_t)strlen(topic->read_string[i]) + 1;
        }
    return size - previousSize;
}

bool QRReadRequest_serialize_topic(ucdrBuffer* writer, const QRReadRequest* topic)
{
    bool success = true;

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->command);

    return success && !writer->error;
}

bool QRReadRequest_deserialize_topic(ucdrBuffer* reader, QRReadRequest* topic)
{
    bool success = true;

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->command);

    return success && !reader->error;
}

uint32_t QRReadRequest_size_of_topic(const QRReadRequest* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

    return size - previousSize;
}

bool QRReadResponse_serialize_topic(ucdrBuffer* writer, const QRReadResponse* topic)
{
    bool success = true;

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->command);

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->code);

    return success && !writer->error;
}

bool QRReadResponse_deserialize_topic(ucdrBuffer* reader, QRReadResponse* topic)
{
    bool success = true;

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->command);

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->code);

    return success && !reader->error;
}

uint32_t QRReadResponse_size_of_topic(const QRReadResponse* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

        size += ucdr_alignment(size, 4) + 4;

    return size - previousSize;
}
