// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dds_AIFaceRecognition.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "dds_AIFaceRecognition.h"

#include <ucdr/microcdr.h>
#include <string.h>



bool AIFaceRecognitionEvent_serialize_topic(ucdrBuffer* writer, const AIFaceRecognitionEvent* topic)
{
    bool success = true;

        success &= TimeStamp_serialize_topic(writer, &topic->stamp);
        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->event);

        success &= ucdr_serialize_string(writer, topic->user_id);

        success &= ucdr_serialize_float(writer, topic->confidence);

        success &= ucdr_serialize_float(writer, topic->spoofing_rate);

    return success && !writer->error;
}

bool AIFaceRecognitionEvent_deserialize_topic(ucdrBuffer* reader, AIFaceRecognitionEvent* topic)
{
    bool success = true;

        success &= TimeStamp_deserialize_topic(reader, &topic->stamp);
        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->event);

        success &= ucdr_deserialize_string(reader, topic->user_id, 255);

        success &= ucdr_deserialize_float(reader, &topic->confidence);

        success &= ucdr_deserialize_float(reader, &topic->spoofing_rate);

    return success && !reader->error;
}

uint32_t AIFaceRecognitionEvent_size_of_topic(const AIFaceRecognitionEvent* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += TimeStamp_size_of_topic(&topic->stamp, size);
        size += ucdr_alignment(size, 4) + 4;

        size += ucdr_alignment(size, 4) + 4 + (uint32_t)strlen(topic->user_id) + 1;

        size += ucdr_alignment(size, 4) + 4;

        size += ucdr_alignment(size, 4) + 4;

    return size - previousSize;
}

bool AIFaceRecognitionRequest_serialize_topic(ucdrBuffer* writer, const AIFaceRecognitionRequest* topic)
{
    bool success = true;

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->command);

        success &= ucdr_serialize_string(writer, topic->user_id);

        success &= ucdr_serialize_uint16_t(writer, topic->timeout_sec);

    return success && !writer->error;
}

bool AIFaceRecognitionRequest_deserialize_topic(ucdrBuffer* reader, AIFaceRecognitionRequest* topic)
{
    bool success = true;

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->command);

        success &= ucdr_deserialize_string(reader, topic->user_id, 255);

        success &= ucdr_deserialize_uint16_t(reader, &topic->timeout_sec);

    return success && !reader->error;
}

uint32_t AIFaceRecognitionRequest_size_of_topic(const AIFaceRecognitionRequest* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

        size += ucdr_alignment(size, 4) + 4 + (uint32_t)strlen(topic->user_id) + 1;

        size += ucdr_alignment(size, 2) + 2;

    return size - previousSize;
}

bool AIFaceRecognitionResponse_serialize_topic(ucdrBuffer* writer, const AIFaceRecognitionResponse* topic)
{
    bool success = true;

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->command);

        success &= ucdr_serialize_uint16_t(writer, topic->user_count);

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->code);

    return success && !writer->error;
}

bool AIFaceRecognitionResponse_deserialize_topic(ucdrBuffer* reader, AIFaceRecognitionResponse* topic)
{
    bool success = true;

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->command);

        success &= ucdr_deserialize_uint16_t(reader, &topic->user_count);

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->code);

    return success && !reader->error;
}

uint32_t AIFaceRecognitionResponse_size_of_topic(const AIFaceRecognitionResponse* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

        size += ucdr_alignment(size, 2) + 2;

        size += ucdr_alignment(size, 4) + 4;

    return size - previousSize;
}
