// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dds_RFID.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "dds_RFID.h"

#include <ucdr/microcdr.h>
#include <string.h>




bool RFIDReadEvent_serialize_topic(ucdrBuffer* writer, const RFIDReadEvent* topic)
{
    bool success = true;

        success &= TimeStamp_serialize_topic(writer, &topic->stamp);
        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->mode);

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->event);

        for(size_t i = 0; i < sizeof(topic->user_id) / 255; ++i)
        {
            success &= ucdr_serialize_string(writer, topic->user_id[i]);
        }
    return success && !writer->error;
}

bool RFIDReadEvent_deserialize_topic(ucdrBuffer* reader, RFIDReadEvent* topic)
{
    bool success = true;

        success &= TimeStamp_deserialize_topic(reader, &topic->stamp);
        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->mode);

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->event);

        for(size_t i = 0; i < sizeof(topic->user_id) / 255; ++i)
        {
            success &= ucdr_deserialize_string(reader, topic->user_id[i], 255);
        }
    return success && !reader->error;
}

uint32_t RFIDReadEvent_size_of_topic(const RFIDReadEvent* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += TimeStamp_size_of_topic(&topic->stamp, size);
        size += ucdr_alignment(size, 4) + 4;

        size += ucdr_alignment(size, 4) + 4;

        for(size_t i = 0; i < sizeof(topic->user_id) / 255; ++i)
        {
            size += ucdr_alignment(size, 4) + 4 + (uint32_t)strlen(topic->user_id[i]) + 1;
        }
    return size - previousSize;
}

bool RFIDRequest_serialize_topic(ucdrBuffer* writer, const RFIDRequest* topic)
{
    bool success = true;

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->command);

        for(size_t i = 0; i < sizeof(topic->security_key) / 255; ++i)
        {
            success &= ucdr_serialize_string(writer, topic->security_key[i]);
        }
    return success && !writer->error;
}

bool RFIDRequest_deserialize_topic(ucdrBuffer* reader, RFIDRequest* topic)
{
    bool success = true;

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->command);

        for(size_t i = 0; i < sizeof(topic->security_key) / 255; ++i)
        {
            success &= ucdr_deserialize_string(reader, topic->security_key[i], 255);
        }
    return success && !reader->error;
}

uint32_t RFIDRequest_size_of_topic(const RFIDRequest* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

        for(size_t i = 0; i < sizeof(topic->security_key) / 255; ++i)
        {
            size += ucdr_alignment(size, 4) + 4 + (uint32_t)strlen(topic->security_key[i]) + 1;
        }
    return size - previousSize;
}

bool RFIDResponse_serialize_topic(ucdrBuffer* writer, const RFIDResponse* topic)
{
    bool success = true;

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->command);

        success &= ucdr_serialize_uint16_t(writer, topic->user_count);

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->code);

    return success && !writer->error;
}

bool RFIDResponse_deserialize_topic(ucdrBuffer* reader, RFIDResponse* topic)
{
    bool success = true;

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->command);

        success &= ucdr_deserialize_uint16_t(reader, &topic->user_count);

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->code);

    return success && !reader->error;
}

uint32_t RFIDResponse_size_of_topic(const RFIDResponse* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

        size += ucdr_alignment(size, 2) + 2;

        size += ucdr_alignment(size, 4) + 4;

    return size - previousSize;
}
