// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dds_AISystem.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "dds_AISystem.h"

#include <ucdr/microcdr.h>
#include <string.h>



bool AISystemEvent_serialize_topic(ucdrBuffer* writer, const AISystemEvent* topic)
{
    bool success = true;

        success &= TimeStamp_serialize_topic(writer, &topic->stamp);
        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->event);

        success &= ucdr_serialize_uint8_t(writer, topic->wifi_connection_status);

        success &= ucdr_serialize_uint8_t(writer, topic->ble_connection_status);

    return success && !writer->error;
}

bool AISystemEvent_deserialize_topic(ucdrBuffer* reader, AISystemEvent* topic)
{
    bool success = true;

        success &= TimeStamp_deserialize_topic(reader, &topic->stamp);
        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->event);

        success &= ucdr_deserialize_uint8_t(reader, &topic->wifi_connection_status);

        success &= ucdr_deserialize_uint8_t(reader, &topic->ble_connection_status);

    return success && !reader->error;
}

uint32_t AISystemEvent_size_of_topic(const AISystemEvent* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += TimeStamp_size_of_topic(&topic->stamp, size);
        size += ucdr_alignment(size, 4) + 4;

        size += ucdr_alignment(size, 1) + 1;

        size += ucdr_alignment(size, 1) + 1;

    return size - previousSize;
}

bool AISystemRequest_serialize_topic(ucdrBuffer* writer, const AISystemRequest* topic)
{
    bool success = true;

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->command);

        success &= ucdr_serialize_uint8_t(writer, topic->wifi_mode);

        success &= ucdr_serialize_uint8_t(writer, topic->ble_mode);

    return success && !writer->error;
}

bool AISystemRequest_deserialize_topic(ucdrBuffer* reader, AISystemRequest* topic)
{
    bool success = true;

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->command);

        success &= ucdr_deserialize_uint8_t(reader, &topic->wifi_mode);

        success &= ucdr_deserialize_uint8_t(reader, &topic->ble_mode);

    return success && !reader->error;
}

uint32_t AISystemRequest_size_of_topic(const AISystemRequest* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

        size += ucdr_alignment(size, 1) + 1;

        size += ucdr_alignment(size, 1) + 1;

    return size - previousSize;
}

bool AISystemResponse_serialize_topic(ucdrBuffer* writer, const AISystemResponse* topic)
{
    bool success = true;

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->command);

        success &= ucdr_serialize_uint32_t(writer, (uint32_t)topic->code);

    return success && !writer->error;
}

bool AISystemResponse_deserialize_topic(ucdrBuffer* reader, AISystemResponse* topic)
{
    bool success = true;

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->command);

        success &= ucdr_deserialize_uint32_t(reader, (uint32_t)&topic->code);

    return success && !reader->error;
}

uint32_t AISystemResponse_size_of_topic(const AISystemResponse* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

        size += ucdr_alignment(size, 4) + 4;

    return size - previousSize;
}
