// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dds_ErrorCode.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _dds_ErrorCode_H_
#define _dds_ErrorCode_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdint.h>
#include <stdbool.h>

typedef enum ErrorCode
{
    SERVICE_OK,
    SERVICE_TIMEOUT,
    SERVICE_REJECT,
    SERVICE_BUSY,
    SERVICE_INVALID_CMD,
    SERVICE_INVALID_VALUE
} ErrorCode;

typedef uint32_t ErrorCode_cdr;

#ifdef __cplusplus
}
#endif

#endif // _dds_ErrorCode_H_